### ISSUE TITLE
Nvidia Cart Page Link only works once and perhaps only on device with Bot Running

### ISSUE THREAD

**Issue by Lennny** [Hari-Nagarajan/nvidia-bot#167]
Even if you previously log in on another device phone etc. Cart link sent via twillio telegram or discord will send you to an empty cart page.

If you remove item from cart and use link it will not work even if you had it previously.

Seems like the add to cart link is now one time use only perhaps.

Must be some kind of change in the api

**Comment by geekyed** [comment]
keep an eye on https://github.com/Hari-Nagarajan/nvidia-bot/tree/nvidia-remote-flag

**Comment by gregoiredelzongle** [comment]
why dont you make a PR out of this ?

**Comment by geekyed** [comment]
@Lennny with the new checkout process its not going to be possible to implement a cart link, would it still be useful toto just have it send a text with a link to the card you're trying to buys page for your locale? I was thinking the notification should have this rather than a cart link anyway now. If you agree let's close this issue and raise a new one to change the link in the notification.

**Comment by worst-mod-confirmed** [comment]
Cart page is kill.
