### ISSUE TITLE
my amazon bot is claiming there is another chrome open

### ISSUE THREAD

**Issue by 9fastcutman** [Hari-Nagarajan/nvidia-bot#302]
![Screenshot_3](https://user-images.githubusercontent.com/74581252/99704225-ef8fec80-2a4c-11eb-911f-89e3b6decfeb.png)
this is all it says before closing even though i check task manager and it doesn't have any open, do i need to update something? or did it just break randomly for me?

**Comment by nitinsaroha** [comment]
This is probably because your chrome auto updated and now there is a version mismatch between chrome and chromedriver which the python app is using. You need to update chromedriver. If you are on mac you can update with brew `brew cask install chromedriver`

@Hari-Nagarajan instead of exiting the program with the generic Exception message, maybe you can log the real exception too. I can do a pull request if you want, I think it's a one line change.

**Comment by worst-mod-confirmed** [comment]
this was fixed with #292, git pull
